version: "3"
services:
  offers-db:
    image: "postgres"
    container_name: "emt1"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=po_offers
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data